import {nodeBaseApi} from "../../api/nodeBaseApi";

const popularBrandApi = nodeBaseApi.injectEndpoints({
    endpoints: (builder) => ({
        popularBrand: builder.query({
            query: () => ({
                url: "/popular-brand", // Endpoint for fetching popular brands
                method: "GET",
            }),
        }),
    }),
    overrideExisting: false, // Set to true if you want to override existing endpoints
});

// Export the hook generated by the API slice
export const { usePopularBrandQuery } = popularBrandApi;

export default popularBrandApi;
